In [2]:
import numpy as np
a = np.zeros(7)
a

array([0., 0., 0., 0., 0., 0., 0.])

In [3]:
a.dtype

dtype('float64')

In [5]:
c=np.empty(8)
c

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 4.24896455e-321, 4.00536721e-307, 2.44771535e-307])

In [8]:
c.shape =(4,2)
c

array([[0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 4.24896455e-321],
       [4.00536721e-307, 2.44771535e-307]])

In [11]:
d= np.linspace(1,5,5)
d

array([1., 2., 3., 4., 5.])

In [12]:
e=np.arange(3,20,5)
e


array([ 3,  8, 13, 18])

In [14]:
f = np.array((4,7,5))
f

array([4, 7, 5])

In [16]:
list= [1,2,3,4,5,6],[1,2,3,4,5,6]
g=np.array((list))
g

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [18]:
g.shape
g

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [19]:
h = np.random.randint(50,size=6)
h

array([28,  8, 16, 25, 30, 20])

In [20]:
h[1]


8

In [21]:
h[0:3]

array([28,  8, 16])

In [22]:
h[-1]

20

In [24]:
h>30

array([False, False, False, False, False, False])

In [25]:
h*2/4

array([14. ,  4. ,  8. , 12.5, 15. , 10. ])

In [26]:
h+50-100

array([-22, -42, -34, -25, -20, -30])

In [27]:
result = np.array([10,20,30,40,50,60,80,90,65])
np.where(result>50,"PASS","FAIL try Again")

array(['FAIL try Again', 'FAIL try Again', 'FAIL try Again',
       'FAIL try Again', 'FAIL try Again', 'PASS', 'PASS', 'PASS', 'PASS'],
      dtype='<U14')

In [39]:
nsteps = 1000
draws = np.random.randint(0,2,size=nsteps)
steps = np.where(draws > 0,1,-1)
walk = steps.cumsum()

walk

array([-1,  0, -1,  0, -1, -2, -3, -2, -3, -2, -1,  0,  1,  2,  1,  2,  3,
        2,  1,  0,  1,  2,  1,  2,  3,  4,  3,  2,  3,  4,  3,  2,  1,  0,
       -1, -2, -1, -2, -3, -4, -3, -2, -3, -2, -1, -2, -3, -4, -3, -2, -1,
        0,  1,  2,  3,  2,  1,  2,  1,  2,  3,  4,  5,  4,  5,  6,  5,  6,
        5,  6,  5,  6,  7,  6,  5,  4,  5,  4,  5,  6,  7,  6,  5,  4,  5,
        4,  3,  4,  5,  6,  7,  6,  5,  4,  5,  6,  7,  8,  9, 10,  9,  8,
        7,  6,  7,  8,  7,  8,  9, 10,  9,  8,  9, 10,  9, 10, 11, 12, 11,
       12, 13, 14, 15, 16, 17, 16, 17, 16, 15, 16, 17, 16, 17, 18, 17, 16,
       15, 16, 15, 14, 15, 14, 13, 12, 11, 12, 13, 14, 15, 16, 17, 16, 17,
       18, 19, 18, 17, 16, 17, 16, 15, 16, 17, 16, 15, 16, 15, 14, 13, 14,
       15, 16, 17, 16, 15, 16, 17, 18, 19, 20, 19, 18, 17, 18, 17, 18, 17,
       16, 15, 16, 15, 16, 15, 16, 15, 16, 17, 16, 17, 18, 19, 18, 17, 18,
       19, 18, 19, 20, 21, 22, 21, 22, 21, 20, 21, 20, 21, 22, 21, 22, 21,
       22, 23, 22, 23, 22

In [46]:
print (walk.min())
print('\n', walk.max())


-8

 29


In [49]:
(np.abs(walk)>= 10).argmax()

99

In [53]:
nwalks = 5000
steps=np.random.normal(loc=0, scale=0.25,size=(nwalks, nsteps))
steps

array([[-0.30507747, -0.23995344,  0.24195561, ...,  0.52605284,
         0.32242156,  0.13916377],
       [-0.14599646,  0.33028479,  0.07621014, ...,  0.30231577,
        -0.17656737, -0.41292003],
       [-0.21772085,  0.29391975, -0.31266875, ...,  0.06389394,
        -0.04665315, -0.3560786 ],
       ...,
       [ 0.09090175,  0.23315987, -0.00128586, ...,  0.25841231,
         0.19941604, -0.13818628],
       [-0.56030127,  0.08972576, -0.11053981, ..., -0.48252043,
         0.20977333,  0.17918154],
       [ 0.05042442,  0.1183612 ,  0.007635  , ..., -0.00681914,
         0.22413723,  0.34140872]])